dist: trusty

sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8
  - openjdk11
  - openjdk15

cache:
  directories:
    - .autoconf
env:
  matrix:
    - TEST_SET="-Ptravis_e2e_skip"
    - TEST_SET="-Ptravis_e2e"
    - TEST_SET="glassfish-copyright:copyright"

install: true

script:
  - bash etc/travis/travis.sh $TEST_SET