github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local execution

title: [Eclipse Jersey]
description: [Eclipse Jersey is a REST framework that provides a JAX-RS (JSR-370) implementation and more]

latestVersion: '2.42'
latest30xVersion: '3.0.13'
latest30xFolder: 'latest30x'
latest3xVersion: '3.1.6'
latest3xFolder: 'latest31x'


links:
  source: https://github.com/eclipse-ee4j/jersey
  docs: https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/index.html
  javadocs: https://eclipse-ee4j.github.io/jersey.github.io/apidocs/latest/jersey/index.html
  download: https://eclipse-ee4j.github.io/jersey/download.html
  mailinglist: https://accounts.eclipse.org/mailing-list/jersey-dev
  hide_issuetracker: true
  honzablog: http://blog.supol.info
  newJerseyURL: https://eclipse-ee4j.github.io/jersey.github.io
  oldJerseyURL: https://jersey.github.io
  #faq: FAQ
