remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [Jersey]
description: [Eclipse Jersey is a REST framework that provides a JAX-RS (JSR-370) implementation and more]

latestVersion: 2.29.1

links:
  source: https://github.com/eclipse-ee4j/jersey
  docs: https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/index.html
  javadocs: https://eclipse-ee4j.github.io/jersey.github.io/apidocs/latest/jersey/index.html
  download: https://github.com/eclipse-ee4j/jersey/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/jersey-dev
  hide_issuetracker: true
  honzablog: http://blog.supol.info
  newJerseyURL: https://eclipse-ee4j.github.io/jersey.github.io
  oldJerseyURL: https://jersey.github.io
  #faq: FAQ
